spring:
  banner:
    image:
      location: classpath:img/IMG_6588.jpg
      bitdepth: 8
      pixelmode: block
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: neko_market_product_route  #商品服务统一路由
          uri: lb://neko-market-product #lb代表loadbalance负载均衡，后面配置上服务名
          predicates:
            - Path=/api/product/**  #代表任何前缀为/api/product请求都会被路由到lb://neko-market-product
          filters:
            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}
  profiles:
    active: dev # 表示开发环境
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8004